// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADb15YsPlG7cCedd4f7PWRqgdNwfjx1l0',
    appId: '1:390338157931:web:d5f78d1bf6c1aa1265c02e',
    messagingSenderId: '390338157931',
    projectId: 'fir-flutter-codelab-24477',
    authDomain: 'fir-flutter-codelab-24477.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-24477.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDw6LwlBfhDXQPx8tBlLjz-G37zt_fnMQ',
    appId: '1:390338157931:android:91a39496800f5dc365c02e',
    messagingSenderId: '390338157931',
    projectId: 'fir-flutter-codelab-24477',
    storageBucket: 'fir-flutter-codelab-24477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMap9uCBVS79FuQUnzHirV3wlJhOFGNoI',
    appId: '1:390338157931:ios:2e4e56ebb33569fe65c02e',
    messagingSenderId: '390338157931',
    projectId: 'fir-flutter-codelab-24477',
    storageBucket: 'fir-flutter-codelab-24477.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMap9uCBVS79FuQUnzHirV3wlJhOFGNoI',
    appId: '1:390338157931:ios:2e4e56ebb33569fe65c02e',
    messagingSenderId: '390338157931',
    projectId: 'fir-flutter-codelab-24477',
    storageBucket: 'fir-flutter-codelab-24477.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}