// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDGlGODsSXgK4Go9bVymboxweexjSP0s',
    appId: '1:1056293605452:web:dfe7654f192f4de77864e9',
    messagingSenderId: '1056293605452',
    projectId: 'finalproject-second-hand-app',
    authDomain: 'finalproject-second-hand-app.firebaseapp.com',
    storageBucket: 'finalproject-second-hand-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAz2GqC3Jh-75QFdyNTfM2aBdZ87yeCw',
    appId: '1:1056293605452:android:186920c8ac6e29997864e9',
    messagingSenderId: '1056293605452',
    projectId: 'finalproject-second-hand-app',
    storageBucket: 'finalproject-second-hand-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XKXHoa_JThLPBTNoqRS5rjq0QaC7U2o',
    appId: '1:1056293605452:ios:5094de2e09fb328a7864e9',
    messagingSenderId: '1056293605452',
    projectId: 'finalproject-second-hand-app',
    storageBucket: 'finalproject-second-hand-app.firebasestorage.app',
    iosBundleId: 'com.xiaotianlyu.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XKXHoa_JThLPBTNoqRS5rjq0QaC7U2o',
    appId: '1:1056293605452:ios:69a5fbe7e61a553f7864e9',
    messagingSenderId: '1056293605452',
    projectId: 'finalproject-second-hand-app',
    storageBucket: 'finalproject-second-hand-app.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaDGlGODsSXgK4Go9bVymboxweexjSP0s',
    appId: '1:1056293605452:web:4718f4b84fa538ae7864e9',
    messagingSenderId: '1056293605452',
    projectId: 'finalproject-second-hand-app',
    authDomain: 'finalproject-second-hand-app.firebaseapp.com',
    storageBucket: 'finalproject-second-hand-app.firebasestorage.app',
  );

}